#!/bin/bash
#SBATCH -N 64
#SBATCH --ntasks-per-node=16
##SBATCH -p priya 
##SBATCH --account=lc_pv
#SBATCH --time=24:00:00
#SBATCH --export=none
#SBATCH --job-name=kpb
##SBATCH --mem-per-cpu=2GB
#SBATCH --output=out1 

source /usr/usc/intel/default/setup.sh 
source /usr/usc/openmpi/default/setup.sh.intel

echo "starting simulation **************************************"
date

srun --ntasks=1024 --mpi=pmi2 ./rxmd > log

date
echo "simulation finished **************************************"
echo
